# Generated by Django 2.2 on 2020-04-22 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='First_name',
            new_name='first_name',
        ),
    ]
