# Generated by Django 2.2 on 2020-04-22 06:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200422_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_pic_upload_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='DOB',
            field=models.DateField(verbose_name='Date Of Birth'),
        ),
    ]
