# Generated by Django 2.2 on 2020-04-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofileforanonymous',
            name='customer_id',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='billingprofileforregisteruser',
            name='customer_id',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
