# Generated by Django 2.2 on 2020-04-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20200419_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=100)),
                ('cust_id', models.CharField(max_length=100)),
                ('country_id', models.CharField(max_length=2)),
                ('brand', models.CharField(max_length=10)),
                ('card_type', models.CharField(max_length=20)),
                ('exp_month', models.IntegerField(max_length=2)),
                ('exp_year', models.IntegerField(max_length=2)),
                ('cadr_last4_digit', models.IntegerField(max_length=4)),
            ],
        ),
    ]
