# Generated by Django 2.2 on 2020-04-20 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20200420_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCardForRegisterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=100)),
                ('country_id', models.CharField(max_length=2)),
                ('brand', models.CharField(max_length=10)),
                ('card_type', models.CharField(max_length=20)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('cadr_last4_digit', models.IntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfileforRegisterUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
