# Generated by Django 2.2 on 2020-04-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='tags.Tags'),
            preserve_default=False,
        ),
    ]
