# Generated by Django 2.2 on 2020-04-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='active_cart',
            field=models.BooleanField(default=True),
        ),
    ]
