# Generated by Django 2.2 on 2020-04-19 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('cart', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForRegisterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='created', max_length=120)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=25, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=99, max_digits=10)),
                ('billing_address', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Billing_Address', to='addresses.Addresses')),
                ('billing_profile_register_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfileforRegisterUser', verbose_name='For Registered User')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('shipping_address', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='addresses.Addresses')),
            ],
        ),
        migrations.CreateModel(
            name='OrderForAnonymusUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='created', max_length=120)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=25, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=99, max_digits=10)),
                ('billing_address', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Billing_Address', to='addresses.AddressForAnonymusUser')),
                ('billing_profile_anynous_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfileForAnonymous', verbose_name='For Anynomus User')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('shipping_address', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='addresses.AddressForAnonymusUser')),
            ],
        ),
    ]
