# Generated by Django 2.2 on 2020-04-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderforanonymususer',
            name='active_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderforregisteruser',
            name='active_order',
            field=models.BooleanField(default=True),
        ),
    ]
